# Build stage
FROM golang:1.23.3-alpine AS builder

WORKDIR /app

# Copia los archivos go.mod y go.sum y descarga dependencias
COPY go.mod go.sum ./
RUN go mod download

# Copia el resto del código fuente
COPY . .

# Compila el binario
RUN go build -o create-service ./cmd/main.go

# Runtime stage
FROM alpine:latest

WORKDIR /app

# Copia el binario compilado y el archivo .env
COPY --from=builder /app/create-service .
COPY ../.env .

# Expone el puerto (ajusta si usas otro)
EXPOSE 3015

# Comando por defecto
CMD ["./create-service"]