# Etapa 1: Build
FROM golang:1.23.3-alpine AS builder

#  Install necessary dependencies
RUN apk add --no-cache git

# set up working directory
WORKDIR /app

# Copy the project files
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Compile the binary
RUN go build -o main cmd/main.go

# Stage 2: Light final image
FROM alpine:3.19

# Set the working directory
WORKDIR /app

# Copy the binary from the build stage
COPY --from=builder /app/main .

# Expose the necessary port
EXPOSE 3015

# Default command when starting the container
CMD ["./main"]
