# Stage 1: Build
FROM golang:1.23.3-alpine AS builder

# Install git and other necessary dependencies
RUN apk add --no-cache git

# Set working directory
WORKDIR /app

# Copy project files
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Compile binary
RUN go build -o main cmd/main.go

# Stage 2: Lightweight final image
FROM alpine:3.19

# Set working directory
WORKDIR /app

# Copy the binary from the build stage
COPY --from=builder /app/main .

# Expose the necessary port
EXPOSE 3018

# Default command when starting the container
CMD ["./main"]
