# Build stage
FROM golang:1.23.3-alpine AS builder

WORKDIR /app

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de dependencias Go
COPY go.mod go.sum ./
RUN go mod download

# Copiar todo el código fuente del proyecto
COPY . .

# Exponer el puerto en el que la aplicación estará disponible
EXPOSE 3018

# Ejecutar la aplicación Go directamente (similar al comando 'go run')
CMD ["go", "run", "cmd/main.go"]