# Etapa 1: Build
FROM golang:1.23.3-alpine AS builder

# Instalar git y otras dependencias necesarias
RUN apk add --no-cache git

# Establecer directorio de trabajo
WORKDIR /app

# Copiar los archivos del proyecto
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Compilar el binario
RUN go build -o main cmd/main.go

# Etapa 2: Imagen final ligera
FROM alpine:3.19

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el binario desde la etapa de construcción
COPY --from=builder /app/main .

# Exponer el puerto necesario
EXPOSE 3016

# Comando por defecto al iniciar el contenedor
CMD ["./main"]
