# Build stage
FROM golang:1.23.3-alpine AS builder

WORKDIR /app

# Copia los archivos de dependencias y descarga módulos
COPY go.mod go.sum ./
RUN go mod download

# Copia el resto del código fuente
COPY . .

# Compila el binario
RUN go build -o get-service ./cmd/main.go

# Runtime stage
FROM alpine:latest

WORKDIR /app

# Copia el binario y el archivo .env
COPY --from=builder /app/get-service .
COPY get-service/.env .

EXPOSE 3016

CMD ["./get-service"]